d /run/remihub-agent/deployment-trigger 0750 alex storage -
r /run/remihub-agent/deployment-trigger/backend-qa.request - - - -
r /run/remihub-agent/deployment-trigger/backend-production.request - - - -
r /run/remihub-agent/deployment-trigger/backend.request - - - -
r /run/remihub-agent/deployment-trigger/android.request - - - -
